# 🤖 Auto-generated by datamodel-codegen
#   version: 0.1.0
#   timestamp: 2025-11-16T20:24:39Z
# ⚠️ Do not edit this file manually


from __future__ import annotations

from typing import Any, Literal, NotRequired, Optional, TypedDict, Union


class AIModel(TypedDict):
    name: str
    source: Literal["mistral", "gemini", "openai", "grok", "self_hosted"]


class Chat(TypedDict):
    id: int
    name: str
    cutoff_date: Optional[str]


class ChatUpload(TypedDict):
    file_id: int
    filename: str
    file_path: str
    created_at: str
    chat_type: str
    processed_at: Optional[str]


class EmbeddingResult(TypedDict):
    summary: str
    title: str
    day: str
    distance: float


class Status(TypedDict):
    status: str
    message: Optional[str]


class User(TypedDict):
    id: int
    first_name: Optional[str]
    last_name: Optional[str]
    chats: list[Chat]
    api_keys: Optional[dict[str, str]]
    meta: Optional[dict[str, Any]]
    uploads: list[ChatUpload]


class UserMeta(TypedDict):
    selected_model: NotRequired[Optional[str]]
    selected_chat_id: NotRequired[Optional[int]]


class ValidationError(TypedDict):
    loc: list[Union[str, int]]
    msg: str
    type: str


class AskQuestion(TypedDict):
    response: str
    results: list[EmbeddingResult]
    question_id: int


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class NewUser(TypedDict):
    telegram_id: str
    first_name: NotRequired[Optional[str]]
    last_name: NotRequired[Optional[str]]
    meta: NotRequired[Optional[UserMeta]]
    api_keys: NotRequired[Optional[dict[str, str]]]
