SET timezone TO 'UTC';
SET schema 'public';
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS general;
CREATE SCHEMA IF NOT EXISTS ai;

CREATE TABLE IF NOT EXISTS general.chat_types
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL CHECK ( length(name) < 1000 ),
    internal_code TEXT UNIQUE NOT NULL
);



CREATE TABLE IF NOT EXISTS general.chats
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamptz NOT NULL DEFAULT now(),
    internal_code TEXT        NOT NULL CHECK ( length(internal_code) < 100 ),
    name          TEXT        NOT NULL CHECK ( length(name) < 1000 )
);



CREATE UNIQUE INDEX IF NOT EXISTS unique_chat_idx ON general.chats (internal_code);

CREATE TABLE IF NOT EXISTS general.chat_users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT        NOT NULL CHECK ( length(username) < 1000 ),
    internal_code  TEXT UNIQUE NOT NULL,
    chat_id        BIGINT      NOT NULL REFERENCES general.chats,
    chat_source_id INT         NOT NULL REFERENCES general.chat_types,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_chat_user_idx ON general.chat_users (chat_source_id, internal_code);


CREATE TABLE IF NOT EXISTS general.chat_messages
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_user_id  BIGINT      NOT NULL REFERENCES general.chat_users,
    chat_id       BIGINT      NOT NULL REFERENCES general.chats,
    sent_at       timestamptz NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    language      VARCHAR(5)  NOT NULL DEFAULT 'en',
    reply_to_id   BIGINT REFERENCES general.chat_messages,
    message       TEXT        NOT NULL CHECK ( length(message) < 10000 ),
    internal_code TEXT        NOT NULL CHECK ( length(internal_code) < 100 ),
    deleted_at    timestamptz
);

BEGIN;
ALTER TABLE general.chat_messages
    DROP CONSTRAINT IF EXISTS unique_message_idx,
    ADD CONSTRAINT unique_message_idx UNIQUE (chat_user_id, internal_code),
    DROP CONSTRAINT IF EXISTS unique_chat_group_idx,
    ADD CONSTRAINT unique_chat_group_idx UNIQUE (id, chat_id);
COMMIT;


--------
-- AI --
--------

CREATE TABLE IF NOT EXISTS ai.message_group_methods
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL CHECK ( length(name) < 1000 ),
    internal_code TEXT        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    meta          JSONB
);

BEGIN;
ALTER TABLE ai.message_group_methods
    DROP CONSTRAINT IF EXISTS unique_message_group_method_idx,
    ADD CONSTRAINT unique_message_group_method_idx UNIQUE (internal_code);
COMMIT;

CREATE TABLE IF NOT EXISTS ai.message_groups
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_method_id BIGINT      NOT NULL REFERENCES ai.message_group_methods,
    internal_code   TEXT        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    summary         TEXT,
    title           TEXT,
    meta            JSONB,
    run_id          UUID,
    chat_id         BIGINT      NOT NULL REFERENCES general.chats
);

BEGIN;
ALTER TABLE ai.message_groups
    DROP CONSTRAINT IF EXISTS internal_code_valid,
    ADD CONSTRAINT internal_code_valid CHECK (length(internal_code) < 100),
    DROP CONSTRAINT IF EXISTS summary_valid,
    ADD CONSTRAINT summary_valid CHECK (length(summary) < 10000),
    DROP CONSTRAINT IF EXISTS title_valid,
    ADD CONSTRAINT title_valid CHECK (length(title) < 1000),
    DROP CONSTRAINT IF EXISTS unique_message_group_idx,
    ADD CONSTRAINT unique_message_group_idx UNIQUE (group_method_id, internal_code);
COMMIT;


CREATE TABLE IF NOT EXISTS ai.message_group_chats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT      NOT NULL REFERENCES ai.message_groups,
    msg_id     BIGINT      NOT NULL REFERENCES general.chat_messages,
    chat_id    BIGINT      NOT NULL REFERENCES general.chats,
    created_at timestamptz NOT NULL DEFAULT now()
);

BEGIN;
ALTER TABLE ai.message_group_chats
    DROP CONSTRAINT IF EXISTS unique_message_group_chat_idx,
    ADD CONSTRAINT unique_message_group_chat_idx UNIQUE (group_id, msg_id);
COMMIT;


CREATE TABLE IF NOT EXISTS ai.mistral_group_embeddings
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT       NOT NULL REFERENCES ai.message_groups,
    embedding         vector(1024) NOT NULL,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    last_processed_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_mistral_summary_idx ON ai.mistral_group_embeddings (group_id);


CREATE TABLE IF NOT EXISTS ai.requests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type  TEXT        NOT NULL,
    total_tokens  INT         NOT NULL,
    input_tokens  INT         NOT NULL,
    output_tokens INT         NOT NULL,
    cached_tokens INT         NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    meta          JSONB,
    payload       JSONB,
    -- The run_id is a UUID that is used to track the request and its associated data.
    run_id        UUID
);


-----------
-- Utils --
-----------


CREATE OR REPLACE VIEW general.message_replies_view as
(
WITH RECURSIVE chat_thread AS (
    -- Base case: select initial messages from the specific date
    SELECT cm.id,
           cm.reply_to_id,
           0 AS depth
    FROM general.chat_messages cm
    WHERE cm.reply_to_id IS NULL -- Only select top-level messages (not replies)
    UNION ALL

    -- Recursive case: select replies to messages in the thread
    SELECT cm.id,
           cm.reply_to_id,
           ct.depth + 1 AS depth
    FROM general.chat_messages cm
             JOIN chat_thread ct ON cm.reply_to_id = ct.id)

-- Select all messages in the threads
SELECT id,
       reply_to_id,
       depth
FROM chat_thread
ORDER BY COALESCE(reply_to_id, id), depth
    );

COMMENT ON VIEW general.message_replies_view IS 'View to get all messages in the threads, with depth.';


-----------
-- Admin --
-- --------

CREATE TABLE IF NOT EXISTS general.users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    TEXT,
    last_name     TEXT,
    telegram_id   TEXT,
    internal_code TEXT,
    api_keys      jsonb,
    meta          jsonb,


--     password_hash TEXT NOT NULL CHECK ( length(password_hash) < 1000 ),
    created_at    timestamptz DEFAULT now()
);

BEGIN;
ALTER TABLE general.users
    DROP CONSTRAINT IF EXISTS unique_users_idx,
    ADD CONSTRAINT unique_users_idx UNIQUE (internal_code),
    DROP CONSTRAINT IF EXISTS first_name_valid,
    ADD CONSTRAINT first_name_valid CHECK ( length(first_name) < 1000 ),
    DROP CONSTRAINT IF EXISTS last_name_valid,
    ADD CONSTRAINT last_name_valid CHECK ( length(last_name) < 1000 ),
    DROP CONSTRAINT IF EXISTS telegram_id_valid,
    ADD CONSTRAINT telegram_id_valid CHECK ( length(telegram_id) < 100 ),
    DROP CONSTRAINT IF EXISTS internal_code_valid,
    ADD CONSTRAINT internal_code_valid CHECK ( length(internal_code) < 1000 );
COMMIT;

CREATE TABLE IF NOT EXISTS general.user_chats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES general.users,
    chat_id      BIGINT NOT NULL REFERENCES general.chats,
    chat_user_id BIGINT NOT NULL REFERENCES general.chat_users,
    created_at   timestamptz DEFAULT now()
);

BEGIN;
ALTER TABLE general.user_chats
    DROP CONSTRAINT IF EXISTS unique_user_chats_idx,
    ADD CONSTRAINT unique_user_chats_idx UNIQUE (user_id, chat_id);
COMMIT;


CREATE TABLE IF NOT EXISTS general.user_questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES general.users,
    meta       JSONB,
    question   TEXT   NOT NULL CHECK ( length(question) < 10000 ),
    feedback   TEXT,
    created_at timestamptz DEFAULT now()
);


CREATE TABLE IF NOT EXISTS general.chat_uploads
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES general.users,
    chat_id      BIGINT REFERENCES general.chats,
    filename     TEXT        NOT NULL,
    mime_type    TEXT        NOT NULL,
    file_size    BIGINT      NOT NULL,
    file_path    TEXT        NOT NULL,
    md5          TEXT        NOT NULL,
    processed_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    chat_type_id INT         NOT NULL REFERENCES general.chat_types
);

BEGIN;
ALTER TABLE general.chat_uploads
    DROP CONSTRAINT IF EXISTS filename_valid,
    ADD CONSTRAINT filename_valid CHECK (length(filename) < 1000),
    DROP CONSTRAINT IF EXISTS file_path_valid,
    ADD CONSTRAINT file_path_valid CHECK (length(file_path) < 1000),
    DROP CONSTRAINT IF EXISTS mime_type_valid,
    ADD CONSTRAINT mime_type_valid CHECK (length(mime_type) < 100),
    DROP CONSTRAINT IF EXISTS md5_valid,
    ADD CONSTRAINT md5_valid CHECK (length(md5) = 32),
    DROP CONSTRAINT IF EXISTS processed_at_valid,
    ADD CONSTRAINT processed_at_valid CHECK ((chat_id is null) = (processed_at is null)),
    DROP CONSTRAINT IF EXISTS unique_chat_uploads,
    ADD CONSTRAINT unique_chat_uploads UNIQUE (md5, user_id);
COMMIT;