-- Description: Create user tables

CREATE TABLE IF NOT EXISTS general.users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    TEXT CONSTRAINT first_name_valid CHECK ( length(first_name) < 1000 ),
    last_name     TEXT CONSTRAINT last_name_valid CHECK ( length(last_name) < 1000 ),
    telegram_id   TEXT CONSTRAINT telegram_id_valid CHECK ( length(telegram_id) < 100 ),
    internal_code TEXT CONSTRAINT internal_code_valid CHECK ( length(internal_code) < 1000 ),
    api_keys      jsonb,
    meta          jsonb,
    created_at    timestamptz DEFAULT now(),

    CONSTRAINT unique_users_idx UNIQUE (internal_code)
);


CREATE TABLE IF NOT EXISTS general.user_questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES general.users,
    meta       JSONB,
    question   TEXT   NOT NULL CHECK ( length(question) < 10000 ),
    feedback   TEXT,
    created_at timestamptz DEFAULT now()
);
