-- Description: Create user tables

CREATE TABLE IF NOT EXISTS general.users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    TEXT,
    last_name     TEXT,
    telegram_id   TEXT,
    internal_code TEXT,
    api_keys      jsonb,
    meta          jsonb,


--     password_hash TEXT NOT NULL CHECK ( length(password_hash) < 1000 ),
    created_at    timestamptz DEFAULT now()
);

BEGIN;
ALTER TABLE general.users
    DROP CONSTRAINT IF EXISTS unique_users_idx,
    ADD CONSTRAINT unique_users_idx UNIQUE (internal_code),
    DROP CONSTRAINT IF EXISTS first_name_valid,
    ADD CONSTRAINT first_name_valid CHECK ( length(first_name) < 1000 ),
    DROP CONSTRAINT IF EXISTS last_name_valid,
    ADD CONSTRAINT last_name_valid CHECK ( length(last_name) < 1000 ),
    DROP CONSTRAINT IF EXISTS telegram_id_valid,
    ADD CONSTRAINT telegram_id_valid CHECK ( length(telegram_id) < 100 ),
    DROP CONSTRAINT IF EXISTS internal_code_valid,
    ADD CONSTRAINT internal_code_valid CHECK ( length(internal_code) < 1000 );
COMMIT;


CREATE TABLE IF NOT EXISTS general.user_questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES general.users,
    meta       JSONB,
    question   TEXT   NOT NULL CHECK ( length(question) < 10000 ),
    feedback   TEXT,
    created_at timestamptz DEFAULT now()
);
