CREATE TABLE IF NOT EXISTS general.chat_types
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL CHECK ( LENGTH(name) < 1000 ),
    internal_code TEXT UNIQUE NOT NULL
);



CREATE TABLE IF NOT EXISTS general.chats
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    internal_code TEXT        NOT NULL CHECK ( LENGTH(internal_code) < 100 ),
    name          TEXT        NOT NULL CHECK ( LENGTH(name) < 1000 ),
    created_by    BIGINT      NOT NULL REFERENCES general.users,
    meta          JSONB
);



CREATE UNIQUE INDEX IF NOT EXISTS unique_chat_idx ON general.chats (internal_code);

CREATE TABLE IF NOT EXISTS general.chat_users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT        NOT NULL CHECK ( LENGTH(username) < 1000 ),
    internal_code  TEXT UNIQUE NOT NULL,
    chat_id        BIGINT      NOT NULL REFERENCES general.chats,
    chat_source_id INT         NOT NULL REFERENCES general.chat_types,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_chat_user_idx ON general.chat_users (chat_source_id, internal_code);


CREATE TABLE IF NOT EXISTS general.chat_messages
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_user_id  BIGINT      NOT NULL REFERENCES general.chat_users,
    chat_id       BIGINT      NOT NULL REFERENCES general.chats,
    sent_at       TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reply_to_id   BIGINT REFERENCES general.chat_messages,
    message       TEXT        NOT NULL CONSTRAINT message_valid CHECK ( LENGTH(message) < 10000 ),
    internal_code TEXT        NOT NULL CONSTRAINT internal_code_valid CHECK ( LENGTH(internal_code) < 100 ),
    deleted_at    TIMESTAMPTZ,

    CONSTRAINT unique_message_idx UNIQUE (chat_user_id, internal_code),
    CONSTRAINT unique_chat_group_idx UNIQUE (id, chat_id)
);



CREATE TABLE IF NOT EXISTS general.chat_uploads
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES general.users,
    chat_id      BIGINT REFERENCES general.chats,
    filename     TEXT        NOT NULL CONSTRAINT filename_valid CHECK (LENGTH(filename) < 1000),
    mime_type    TEXT        NOT NULL CONSTRAINT mime_type_valid CHECK (LENGTH(mime_type) < 100),
    file_size    BIGINT      NOT NULL,
    file_path    TEXT        NOT NULL CONSTRAINT file_path_valid CHECK (LENGTH(file_path) < 1000),
    md5          TEXT        NOT NULL CONSTRAINT md5_valid CHECK (LENGTH(md5) = 32),
    processed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    chat_type_id INT         NOT NULL REFERENCES general.chat_types,

    CONSTRAINT processed_at_valid CHECK ((chat_id IS NULL) = (processed_at IS NULL)),
    CONSTRAINT unique_chat_uploads UNIQUE (md5, user_id)
);


-----------
-- Utils --
-----------


CREATE OR REPLACE VIEW general.message_replies_view AS
(
WITH RECURSIVE chat_thread AS (
    -- Base case: select initial messages from the specific date
    SELECT cm.id,
           cm.reply_to_id,
           0 AS depth
    FROM general.chat_messages cm
    WHERE cm.reply_to_id IS NULL -- Only select top-level messages (not replies)
    UNION ALL

    -- Recursive case: select replies to messages in the thread
    SELECT cm.id,
           cm.reply_to_id,
           ct.depth + 1 AS depth
    FROM general.chat_messages cm
             JOIN chat_thread ct ON cm.reply_to_id = ct.id)

-- Select all messages in the threads
SELECT id,
       reply_to_id,
       depth
FROM chat_thread
ORDER BY COALESCE(reply_to_id, id), depth
    );

COMMENT ON VIEW general.message_replies_view IS 'View to get all messages in the threads, with depth.';
