
--------
-- AI --
--------

CREATE TABLE IF NOT EXISTS ai.message_group_methods
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL CHECK ( length(name) < 1000 ),
    internal_code TEXT        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    meta          JSONB
);

BEGIN;
ALTER TABLE ai.message_group_methods
    DROP CONSTRAINT IF EXISTS unique_message_group_method_idx,
    ADD CONSTRAINT unique_message_group_method_idx UNIQUE (internal_code);
COMMIT;

CREATE TABLE IF NOT EXISTS ai.message_groups
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_method_id BIGINT      NOT NULL REFERENCES ai.message_group_methods,
    internal_code   TEXT        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    summary         TEXT,
    title           TEXT,
    meta            JSONB,
    run_id          UUID,
    chat_id         BIGINT      NOT NULL REFERENCES general.chats
);

BEGIN;
ALTER TABLE ai.message_groups
    DROP CONSTRAINT IF EXISTS internal_code_valid,
    ADD CONSTRAINT internal_code_valid CHECK (length(internal_code) < 100),
    DROP CONSTRAINT IF EXISTS summary_valid,
    ADD CONSTRAINT summary_valid CHECK (length(summary) < 10000),
    DROP CONSTRAINT IF EXISTS title_valid,
    ADD CONSTRAINT title_valid CHECK (length(title) < 1000),
    DROP CONSTRAINT IF EXISTS unique_message_group_idx,
    ADD CONSTRAINT unique_message_group_idx UNIQUE (group_method_id, internal_code);
COMMIT;


CREATE TABLE IF NOT EXISTS ai.message_group_chats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT      NOT NULL REFERENCES ai.message_groups,
    msg_id     BIGINT      NOT NULL REFERENCES general.chat_messages,
    chat_id    BIGINT      NOT NULL REFERENCES general.chats,
    created_at timestamptz NOT NULL DEFAULT now()
);

BEGIN;
ALTER TABLE ai.message_group_chats
    DROP CONSTRAINT IF EXISTS unique_message_group_chat_idx,
    ADD CONSTRAINT unique_message_group_chat_idx UNIQUE (group_id, msg_id);
COMMIT;


CREATE TABLE IF NOT EXISTS ai.mistral_group_embeddings
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT       NOT NULL REFERENCES ai.message_groups,
    embedding         vector(1024) NOT NULL,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    last_processed_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_mistral_summary_idx ON ai.mistral_group_embeddings (group_id);


CREATE TABLE IF NOT EXISTS ai.requests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type  TEXT        NOT NULL,
    total_tokens  INT         NOT NULL,
    input_tokens  INT         NOT NULL,
    output_tokens INT         NOT NULL,
    cached_tokens INT         NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    meta          JSONB,
    payload       JSONB,
    -- The run_id is a UUID that is used to track the request and its associated data.
    run_id        UUID,
    user_id       BIGINT      NOT NULL REFERENCES general.users
);
