
CREATE TABLE IF NOT EXISTS general.user_chats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES general.users,
    chat_id      BIGINT NOT NULL REFERENCES general.chats,
    chat_user_id BIGINT NOT NULL REFERENCES general.chat_users,
    created_at   timestamptz DEFAULT now(),

    CONSTRAINT unique_user_chats_idx UNIQUE (user_id, chat_id)
);
